<?php

namespace Vodapay\Vodapay\Block\Payment;


class Request extends \Magento\Framework\View\Element\Template
{

    /** @var \Vodapay\Vodapay\Model\Vodapay $_paymentMethod*/
    protected $_paymentMethod;

    /**
     * @var \Magento\Sales\Model\OrderFactory
     */
    protected $_orderFactory;

    /**
     * @var \Magento\Checkout\Model\Session
     */
    protected $_checkoutSession;

    /** @var \Magento\Framework\Filesystem\Directory\ReadFactory  $readFactory*/
    protected $readFactory;

    /** @var \Magento\Framework\Module\Dir\Reader $reader */
    protected $reader;

    /**
     * @param \Magento\Framework\View\Element\Template\Context $context
     * @param \Magento\Sales\Model\OrderFactory $orderFactory
     * @param \Magento\Checkout\Model\Session $checkoutSession
     * @param \Vodapay\Vodapay\Helper\Data $pfHelper
     * @param \Magento\Framework\Filesystem\Directory\ReadFactory $readFactory
     * @param \Magento\Framework\Module\Dir\Reader $reader
     * @param \Vodapay\Vodapay\Model\Vodapay $paymentMethod
     * @param array $data
     */
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Sales\Model\OrderFactory $orderFactory,
        \Magento\Checkout\Model\Session $checkoutSession,
        \Vodapay\Vodapay\Helper\Data $pfHelper,
        \Magento\Framework\Filesystem\Directory\ReadFactory $readFactory,
        \Magento\Framework\Module\Dir\Reader $reader,
        \Vodapay\Vodapay\Model\Vodapay $paymentMethod,
        array $data = []
    ) {
        $this->_hssHelper = $pfHelper;
        $this->_orderFactory = $orderFactory;
        $this->_checkoutSession = $checkoutSession;
        parent::__construct($context, $data);
        $this->_isScopePrivate = true;
        $this->readFactory = $readFactory;
        $this->reader = $reader;
        $this->_paymentMethod = $paymentMethod;
    }

    public function _prepareLayout()
    {
        $this->setMessage('Redirecting to Vodapay')
            ->setId( 'vodapay_checkout' )
            ->setName( 'vodapay_checkout' )
            ->setFormMethod( 'POST' )
            ->setFormAction($this->_paymentMethod->getVodapayUrl())
            ->setSubmitForm('<script type="text/javascript">document.getElementById( "vodapay_checkout" ).submit();</script>');

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

}
